# Generated by Django 4.1 on 2023-02-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Spotify',
        ),
    ]
